---
kind: pipeline
name: default

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/alpine/git
    commands:
      - git clone https://github.com/bdebyl/docker-alpine-git.git .
      - git checkout $DRONE_COMMIT
      - echo -n "0.1.$DRONE_BUILD_NUMBER" > .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/alpine-git

---
kind: signature
hmac: 73c6cc283695c32ca91abb922d37150669279dba98d5696222c0fcb2f4b26b18

...
