---
kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/alpine-git

---
kind: signature
hmac: de5c53c685f21e16ef4e63b806ab93f4128d2e0fd5ebe0e0e3d8b00d79de78a3

...
