---
kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/alpine-git
      auto_tag: true

---
kind: signature
hmac: f5cbb9a31c11d87b2881fab3bb1d3eb39bf6278624fd700aada89cee9e2ff322

...
